name: CI - Testes e Análise Estática

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar versão do PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Instalar dependências do Composer
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copiar .env para testes
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Gerar chave da aplicação
        run: php artisan key:generate

      - name: Esperar MySQL ficar pronto
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          echo "Aguardando MySQL..."
          for i in {1..15}; do
            if mysqladmin ping -h"mysql" --silent; then
              echo "MySQL está pronto!"
              break
            fi
            echo "Tentando novamente..."
            sleep 2
          done

      - name: Configurar banco de dados de testes
        run: php artisan migrate --force

      - name: Rodar PHPUnit
        run: vendor/bin/phpunit --testdox

      - name: Rodar análise estática (PHPStan)
        run: vendor/bin/phpstan analyse --memory-limit=1G

      - name: Rodar Laravel Pint
        run: vendor/bin/pint --test
